version: "3.5"
services:
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
    command: "-m 8222"
  prometheus-nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: "-varz http://nats:8222"
    ports:
      - "7777:7777"
    depends_on:
      - nats
  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    depends_on:
      - prometheus-nats-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: